### ISSUE TITLE
StyleC.CSS

### ISSUE THREAD

**Issue by notWizzy** [notWizzy/p01#4]
Extra Credit
Create a third stylesheet styleC.css that utilizes 2 of the following:

gradients
transitions
animations
web fonts
shadows

**Comment by dmool** [comment]
Everything done except for letter F

**Comment by dmool** [comment]
utilizes web fonts, shadows, and gradients

**Comment by notWizzy** [comment]
Added the following for class = "letterF" :

.letterF{
    background: linear-gradient(to bottom, yellow, blue 50%, green);
    text-shadow: red 5px 5px 5px;
}

**Comment by dmool** [comment]
added a transition and an animation to the code.
